# 通过 Github action， 在仓库的每一次 commit 后自动同步到 Gitee 上
name: sync2gitee
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@132b206a796926508b73fe82e9f3bb0969a3add6
      with:
        src: 'github/${{ github.repository_owner }}'
        dst: 'gitee/${{ secrets.GITEE_USER }}'
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: ${{ github.event.repository.name }}
        debug: true
